# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# Copy source
COPY mc_math/ /app/

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --ignore-requires-python \
       httpx>=0.28.1 \
       "mcp[cli]>=1.9.1" \
       openai>=1.82.0

# Default command to run the MCP server
CMD ["python", "main.py"]
